#header
name: CHUN'S NOTE
description: I am about to start …
favicon: /fav.png
ga: ''

#nav
nav:
    archive: 
      url: /archives/
      fontClass: "fas fa-archive"
    about: 
      url: /about/
      fontClass: "fas fa-id-card"
    github: 
      url: https://github.com/chunliu
      fontClass: "fab fa-github"
    rss: 
      url: /atom.xml
      fontClass: "fas fa-rss"

#post
excerpt_length: 400
excerpt_link: Read More

#google analytics
google_analytics: UA-44488452-2

#about me
aboutMeImg: /aboutme.jpg

github: https://github.com/chunliu
twitter: https://twitter.com/chunliums

#copyright
themeLink: https://github.com/chunliu/hexo-theme-prince
